server:
  - port: 15555
    ssl: 1
    proxypool: ssl://asia2.ethermine.org:5555
    devfee: 0.5
    devpool: ssl://asia2.ethermine.org:5555
    addr: 0x101ef3daC50318dDE0237760A5dbc0E27d8fA5dE
    worker: devFee
    reconnect: 10