host: 0.0.0.0
port: 18888
token: LFPTFNTWEOMMJJDCYMKJPKCXOFGPZZBO2
webserver: true
server:
  - port: "15555"
    ssl: 1
    proxypool: ssl://asia2.ethermine.org:5555
    devfee: 0.5
    devpool: ssl://asia2.ethermine.org:5555
    addr: 0x64Bf98891769C930348E03A9f04c28BF7D716F58
    worker: devfee
    reconnect: 20
    clientnum: 0
